---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: ~/k3s_install.sh
    mode: '0755'

- name: Copy k3s_token to workers
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/k3s_token"
    dest: /home/pi/k3s_token
    mode: '0600'

- name: Check if k3s_token file exists
  ansible.builtin.stat:
    path: /home/pi/k3s_token
  register: k3s_token_stat

- name: Debug k3s_token file
  ansible.builtin.debug:
    msg: "k3s_token file exists: {{ k3s_token_stat.stat.exists }}"

- name: Read k3s token
  ansible.builtin.slurp:
    src: /home/pi/k3s_token
  register: k3s_token_slurp
  when: k3s_token_stat.stat.exists

- name: Decode k3s token
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token_slurp.content | b64decode }}"
  when: k3s_token_stat.stat.exists

- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Debug K3s installation status
  ansible.builtin.debug:
    msg: "K3s is already installed: {{ k3s_installed.stat.exists }}"

- name: Install K3s on worker nodes
  ansible.builtin.shell: |
    K3S_URL="{{ k3s_master_url }}" \
    K3S_TOKEN="{{ k3s_token }}" \
    ~/k3s_install.sh >> /home/pi/k3s_install_log.txt 2>&1
  args:
    chdir: "~"
    creates: /usr/local/bin/k3s
  when:
    - not k3s_installed.stat.exists
    - k3s_token_stat.stat.exists
