---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: ~/k3s_install.sh
    mode: '0755'

- name: Install k3s on master node
  ansible.builtin.shell: >
    ~/k3s_install.sh >> ~/k3s_install_log.txt
  args:
    chdir: "~"
    creates: /usr/local/bin/k3s

- name: Retrieve k3s token
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token_content
  changed_when: false

- name: Set k3s token fact
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token_content.stdout }}"

- name: Save k3s token to a file for workers
  ansible.builtin.copy:
    content: "{{ k3s_token }}"
    dest: /home/pi/k3s_token
    mode: '0600'

- name: Fetch kubeconfig file from master node
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/kubeconfig/k3s.yaml"
    flat: yes
  delegate_to: master-node

- name: Set permissions on k3s_token on master node
  ansible.builtin.file:
    path: /home/pi/k3s_token
    owner: pi
    group: pi"
    mode: '0600'
  delegate_to: master-node
  run_once: true

- name: Transfer kubeconfig file to local machine
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/kubeconfig/k3s.yaml"
    dest: "{{ playbook_dir }}/kubeconfig/"
  delegate_to: localhost

- name: Ensure .kube directory exists for pi user
  ansible.builtin.file:
    path: /home/pi/.kube
    state: directory
    owner: pi
    group: pi
    mode: '0755'
  become: true

- name: Copy kubeconfig to pi user's .kube directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/kubeconfig/k3s.yaml"
    dest: /home/pi/.kube/config
    owner: pi
    group: pi
    mode: '0644'
  become: true