---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Perform a full distribution upgrade
  apt:
    upgrade: full

- name: Install vim
  apt:
    name: vim
    state: present

- name: Ensure required dependencies are installed.
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-openshift
      - python3-yaml
      - build-essential
      - golang
      - git
    state: present
  become: true