---
- name: Update and install common packages on all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Install k3s on the master node
  hosts: master
  become: yes
  roles:
    - k3s_master

- name: Install k3s on worker nodes
  hosts: workers
  become: yes
  roles:
    - k3s_worker
